#!/usr/bin/env python3
"""Regenerate the data-driven paper figures in one shot.

Reads experimental outputs from `data/english_panel/` and
`data/multilingual_panel/` (produced by
`code/notebooks/full_paper_pipeline.ipynb`) and writes the figures to
`data/figures/`:

    fig2_main_curves     — adjacent / displaced (5 reps) / 13-model heatmap
    fig3_crosslingual    — 4-model × 4-language heatmap of per-word drop
    fig4_ablation        — six-condition causal ablation
    fig5_mechanism       — per-target-token attention / block budget / slot-state
    fig6_layerwise       — per-layer attention vs 1/N reference (appendix)
    fig7_framepragm      — frame-pragmatics ablation (appendix)

Figure 1 (the two-probe-design schematic) is a hand-authored static asset
shipped as `data/figures/fig1_probe_schematic.{pdf,svg}` and is NOT
regenerated by this script.

Usage:
    python code/src/make_figures.py                # regenerate all data figures
    python code/src/make_figures.py fig2 fig4      # regenerate a subset

Figures 2/4/5 share a hand-curated 13-model panel (PANEL) and a 4-model
mechanism subset (MECH_MODELS); figure 3 uses the multilingual panel.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.lines import Line2D

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent.parent.parent
DATA = ROOT / "data" / "english_panel"
SUMMARY = DATA / "summary"
MULTILING = ROOT / "data" / "multilingual_panel"
FIGS = ROOT / "data" / "figures"
REPORTS = ROOT / "data" / "reports"

FIGS.mkdir(parents=True, exist_ok=True)
REPORTS.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Shared panel definitions
# ---------------------------------------------------------------------------
NS = [0, 1, 3, 5, 10, 20, 30]
NS_NONZERO = [n for n in NS if n > 0]

PANEL = [
    ("answerdotai/ModernBERT-base",      "ModernBERT-base",     "MLM", "#1f77b4"),
    ("answerdotai/ModernBERT-large",     "ModernBERT-large",    "MLM", "#3a6db1"),
    ("Qwen/Qwen2.5-0.5B",                "Qwen2.5-0.5B",        "CLM", "#ffe6cc"),
    ("Qwen/Qwen2.5-1.5B",                "Qwen2.5-1.5B",        "CLM", "#ffbf80"),
    ("Qwen/Qwen2.5-3B",                  "Qwen2.5-3B",          "CLM", "#ff9933"),
    ("Qwen/Qwen2.5-7B",                  "Qwen2.5-7B",          "CLM", "#cc6600"),
    ("Qwen/Qwen2.5-7B-Instruct",         "Qwen2.5-7B-Inst",     "CLM", "#993300"),
    ("Qwen/Qwen2.5-14B",                 "Qwen2.5-14B",         "CLM", "#660000"),
    ("HuggingFaceTB/SmolLM2-360M",       "SmolLM2-360M",        "CLM", "#aec7e8"),
    ("HuggingFaceTB/SmolLM2-1.7B",       "SmolLM2-1.7B",        "CLM", "#1f77b4"),
    ("microsoft/Phi-3.5-mini-instruct",  "Phi-3.5-mini",        "CLM", "#9467bd"),
    ("allenai/OLMo-2-0425-1B",           "OLMo-2-1B",           "CLM", "#98df8a"),
    ("allenai/OLMo-2-1124-7B",           "OLMo-2-7B",           "CLM", "#2ca02c"),
]
ID_TO = {mid: (short, fam, color) for mid, short, fam, color in PANEL}

# Mechanism-probe subset (4 models spanning objectives + scales).
MECH_MODELS = [
    ("answerdotai/ModernBERT-large", "ModernBERT-large", "MLM", "#3a6db1"),
    ("Qwen/Qwen2.5-1.5B",            "Qwen2.5-1.5B",     "CLM", "#ffbf80"),
    ("Qwen/Qwen2.5-7B",              "Qwen2.5-7B",       "CLM", "#cc6600"),
    ("allenai/OLMo-2-1124-7B",       "OLMo-2-7B",        "CLM", "#2ca02c"),
]

# Five representative models for Figure 2(b), spanning the panel peak-N range.
FIG2B_REPS = [
    ("answerdotai/ModernBERT-large", "ModernBERT-large",   "MLM", "#3a6db1", "-"),
    ("Qwen/Qwen2.5-14B",             "Qwen2.5-14B",        "CLM", "#660000", "--"),
    ("Qwen/Qwen2.5-7B-Instruct",     "Qwen2.5-7B-Inst",    "CLM", "#cc6600", "--"),
    ("HuggingFaceTB/SmolLM2-360M",   "SmolLM2-360M",       "CLM", "#aec7e8", "--"),
    ("HuggingFaceTB/SmolLM2-1.7B",   "SmolLM2-1.7B",       "CLM", "#1f77b4", "--"),
]

matplotlib.rcParams.update({
    "font.size": 10.5,
    "axes.titlesize": 11,
    "axes.labelsize": 10.5,
    "xtick.labelsize": 9.5,
    "ytick.labelsize": 9.5,
    "legend.fontsize": 9,
})


def boot_ci(values, n=500, seed=42):
    rng = np.random.default_rng(seed)
    if len(values) == 0:
        return float("nan"), float("nan"), float("nan")
    boots = [float(rng.choice(values, size=len(values), replace=True).mean())
             for _ in range(n)]
    return (float(np.mean(values)),
            float(np.percentile(boots, 2.5)),
            float(np.percentile(boots, 97.5)))


def _safe(mid: str) -> str:
    return mid.replace("/", "__")


# ===========================================================================
# Figure 2 — adjacent / displaced (5 reps) / 13-model heatmap
# ===========================================================================
def fig2_main_curves():
    disp = pd.read_parquet(SUMMARY / "displaced_all.parquet")
    fig, axes = plt.subplots(1, 3, figsize=(20.0, 5.0),
                             gridspec_kw=dict(width_ratios=[1.70, 1.70, 1.40]))

    # (a) Adjacent baseline
    ax = axes[0]
    adj_files = sorted((DATA / "adjacent").glob("adjacent__*.parquet"))
    adj = (pd.concat([pd.read_parquet(f) for f in adj_files], ignore_index=True)
           if adj_files else pd.DataFrame())
    if not adj.empty:
        for mid in [m for m, _, _, _ in PANEL if m in adj["model"].unique()]:
            short, fam, color = ID_TO[mid]
            sub = adj[adj.model == mid]
            curve = sub.groupby("N")["target_prob"].mean().sort_index()
            ax.plot(curve.index, curve.values, marker="o",
                    label=f"{short} ({fam})",
                    linestyle="-" if fam == "MLM" else "--",
                    color=color, linewidth=2.2)
    ax.set_xlabel("repetitions in prefix $N$")
    ax.set_ylabel("mean P(target)")
    ax.set_title("(a) Adjacent baseline: monotonic priming")
    ax.legend(loc="lower right", framealpha=0.92, fontsize=9)
    ax.grid(True, alpha=0.3)

    # (b) Displaced F0 — 5 representative models
    ax = axes[1]
    for mid, short, fam, color, ls in FIG2B_REPS:
        sub = disp[(disp.model == mid) & (disp.frame_id == "F0")]
        if sub.empty or sub["target_prob"].isna().all():
            continue
        curve = sub.groupby("N")["target_prob"].mean().sort_index()
        ax.plot(curve.index, curve.values, marker="o",
                label=f"{short} ({fam})",
                linestyle=ls, color=color, linewidth=2.2, markersize=5)
    ax.set_xlabel("repetitions in prefix $N$")
    ax.set_ylabel("mean P(target)")
    ax.set_title("(b) Displaced probe F0 (5 representative models)")
    ax.legend(loc="upper right", fontsize=9, framealpha=0.92)
    ax.grid(True, alpha=0.3)

    # (c) Heatmap across all 13 panel models
    ax = axes[2]
    rows = []
    NS_NZ = [1, 3, 5, 10, 20, 30]
    for mid, short, fam, color in PANEL:
        sub = disp[(disp.model == mid) & (disp.frame_id == "F0")]
        if sub.empty or sub["target_prob"].isna().all():
            continue
        curve = sub.groupby("N")["target_prob"].mean()
        vals = np.array([curve.get(n, np.nan) for n in NS_NZ])
        peak = np.nanmax(vals)
        if peak is None or peak <= 0 or np.isnan(peak):
            continue
        norm = vals / peak
        p30 = vals[-1] if not np.isnan(vals[-1]) else 0.0
        drop = (peak - p30) / peak if peak > 0 else 0.0
        rows.append({"model": short, "fam": fam, "drop": drop, "norm": norm,
                     "peak_n": NS_NZ[int(np.nanargmax(vals))]})
    rows = sorted(rows, key=lambda r: -r["drop"])
    M = np.array([r["norm"] for r in rows])
    labels = [f"{r['model']} ({r['fam']})" for r in rows]
    im = ax.imshow(M, aspect="auto", cmap="magma", vmin=0.0, vmax=1.0,
                   extent=[-0.5, len(NS_NZ) - 0.5, len(rows) - 0.5, -0.5])
    ax.set_xticks(range(len(NS_NZ)))
    ax.set_xticklabels([str(n) for n in NS_NZ])
    ax.set_yticks(range(len(rows)))
    ax.set_yticklabels(labels, fontsize=8.5)
    ax.set_xlabel("$N$ (repetitions)")
    ax.set_title("(c) Peak-normalised P(target) across all 13 panel models")
    for i, r in enumerate(rows):
        peak_idx = NS_NZ.index(r["peak_n"])
        ax.plot(peak_idx, i, marker="o", color="white", markersize=4.0,
                markeredgecolor="black", markeredgewidth=0.7)
    cbar = fig.colorbar(im, ax=ax, fraction=0.04, pad=0.02)
    cbar.set_label("P(target) / per-curve peak", fontsize=9)
    cbar.ax.tick_params(labelsize=8)

    fig.tight_layout()
    fig.savefig(FIGS / "fig2_main_curves.png", dpi=160, bbox_inches="tight")
    fig.savefig(FIGS / "fig2_main_curves.pdf", bbox_inches="tight")
    plt.close(fig)
    print(f"  fig2 → {FIGS / 'fig2_main_curves.png'}")


# ===========================================================================
# Figure 3 — cross-lingual replication (4 models × 4 languages × 3 frames)
# ===========================================================================
def fig3_crosslingual():
    src = MULTILING / "summary" / "model_lang_frame_summary.csv"
    if not src.exists():
        print(f"  no multilingual summary at {src}; skipping fig3"); return
    df = pd.read_csv(src)

    # Row order: MLM block first (XLM-R-base, large), then CLM block (Qwen 1.5B, 7B).
    model_order = ["xlm-roberta-base", "xlm-roberta-large",
                   "Qwen2.5-1.5B", "Qwen2.5-7B"]
    model_labels = {"xlm-roberta-base":  "XLM-R-base (MLM)",
                    "xlm-roberta-large": "XLM-R-large (MLM)",
                    "Qwen2.5-1.5B":      "Qwen2.5-1.5B (CLM)",
                    "Qwen2.5-7B":        "Qwen2.5-7B (CLM)"}

    # Column order: Spanish, German, French, Chinese.
    lang_order = ["es", "de", "fr", "zh"]
    lang_labels = {"es": "Spanish", "de": "German", "fr": "French",
                   "zh": "Chinese"}

    frames = ["F0", "F1", "F2"]

    fig, axes = plt.subplots(1, 3, figsize=(13.5, 3.6),
                             gridspec_kw=dict(width_ratios=[1, 1, 1.1]))

    # Warm sequential colormap: light cream → deep accent.
    cmap = LinearSegmentedColormap.from_list(
        "cl_drop", [(1.00, 0.95, 0.86),
                    (0.95, 0.75, 0.55),
                    (0.83, 0.47, 0.25),
                    (0.55, 0.20, 0.10)])
    vmin, vmax = 0.0, 0.9

    last_im = None
    for ax, frame in zip(axes, frames):
        sub = df[df.frame_id == frame].copy()
        M = np.full((len(model_order), len(lang_order)), np.nan)
        for i, mid in enumerate(model_order):
            for j, lang in enumerate(lang_order):
                row = sub[(sub.model == mid) & (sub.lang == lang)]
                if not row.empty:
                    M[i, j] = float(row["drop_mean"].values[0])
        last_im = ax.imshow(M, aspect="auto", cmap=cmap, vmin=vmin, vmax=vmax)

        # Annotate each cell.
        for i in range(len(model_order)):
            for j in range(len(lang_order)):
                v = M[i, j]
                if np.isnan(v):
                    ax.text(j, i, "n/a", ha="center", va="center",
                            fontsize=8.5, color="#777")
                else:
                    txt_color = "white" if v > 0.55 else "#2a2a28"
                    ax.text(j, i, f"{v:.2f}", ha="center", va="center",
                            fontsize=9, color=txt_color, fontweight="medium")

        ax.set_xticks(range(len(lang_order)))
        ax.set_xticklabels([lang_labels[l] for l in lang_order],
                           fontsize=9.5)
        if ax is axes[0]:
            ax.set_yticks(range(len(model_order)))
            ax.set_yticklabels([model_labels[m] for m in model_order],
                               fontsize=9.5)
        else:
            ax.set_yticks([])
        ax.set_title(f"({chr(ord('a') + frames.index(frame))}) {frame}",
                     fontsize=11)
        # Light gridlines between cells.
        ax.set_xticks(np.arange(-0.5, len(lang_order), 1), minor=True)
        ax.set_yticks(np.arange(-0.5, len(model_order), 1), minor=True)
        ax.grid(which="minor", color="white", linestyle="-", linewidth=1)
        ax.tick_params(which="minor", length=0)

    if last_im is not None:
        cbar = fig.colorbar(last_im, ax=axes[-1], fraction=0.045, pad=0.04)
        cbar.set_label("per-word drop", fontsize=9.5)
        cbar.ax.tick_params(labelsize=8.5)

    fig.tight_layout()
    fig.savefig(FIGS / "fig3_crosslingual.png", dpi=160, bbox_inches="tight")
    fig.savefig(FIGS / "fig3_crosslingual.pdf", bbox_inches="tight")
    plt.close(fig)
    print(f"  fig3 → {FIGS / 'fig3_crosslingual.png'}")


# ===========================================================================
# Figure 4 — six-condition causal ablation
# ===========================================================================
def fig4_ablation():
    abl_files = sorted((DATA / "ablation").glob("ablation__*.parquet"))
    if not abl_files:
        print("  no ablation files; skipping fig3"); return
    abl = pd.concat([pd.read_parquet(f) for f in abl_files], ignore_index=True)
    cond_order = ["full_repeat_N30", "truncate_to_N3", "delete_repeat_block",
                  "random_filler_same_length", "unique_semantic_filler",
                  "repeat_unrelated_N30"]
    cond_labels = ["Full N=30", "Trunc. N=3", "Deleted",
                   "Random", "Semantic", "Table×30"]

    models = [(m, s, f, c) for (m, s, f, c) in MECH_MODELS if m in abl["model"].unique()]
    fig, axes = plt.subplots(1, 3, figsize=(15.4, 5.0))
    width = 0.8 / max(1, len(models))
    x = np.arange(len(cond_order))

    # (a) target prob with CIs
    ax = axes[0]
    for i, (mid, short, fam, color) in enumerate(models):
        sub = abl[abl.model == mid]
        means, los, his = [], [], []
        for c in cond_order:
            v = sub[sub.condition == c]["target_prob"].dropna().values
            mn, lo, hi = boot_ci(v, n=300, seed=42)
            means.append(mn); los.append(lo); his.append(hi)
        means, los, his = np.array(means), np.array(los), np.array(his)
        offs = (i - len(models) / 2 + 0.5) * width
        ax.bar(x + offs, means, width=width,
               yerr=[np.nan_to_num(means - los, nan=0.0),
                     np.nan_to_num(his - means, nan=0.0)],
               capsize=2.5, label=short, color=color)
    ax.set_xticks(x); ax.set_xticklabels(cond_labels, rotation=22, ha="right")
    ax.set_ylabel("mean P(target) (95% CI)")
    ax.set_title("(a) Target probability")
    ax.grid(True, alpha=0.3, axis="y")
    ax.set_xlim(-0.5, len(cond_order) - 0.5)

    # (b) ΣP(synonyms)
    ax = axes[1]
    for i, (mid, short, fam, color) in enumerate(models):
        sub = abl[abl.model == mid]
        means = []
        for c in cond_order:
            v = sub[sub.condition == c]["sum_synonym_prob"].dropna().values
            means.append(float(np.mean(v)) if len(v) else float("nan"))
        offs = (i - len(models) / 2 + 0.5) * width
        ax.bar(x + offs, means, width=width, color=color)
    ax.set_xticks(x); ax.set_xticklabels(cond_labels, rotation=22, ha="right")
    ax.set_ylabel(r"mean $\Sigma\,P(\mathrm{synonyms})$")
    ax.set_title("(b) Semantic-field mass")
    ax.grid(True, alpha=0.3, axis="y")
    ax.set_xlim(-0.5, len(cond_order) - 0.5)

    # (c) target rank (log)
    ax = axes[2]
    for i, (mid, short, fam, color) in enumerate(models):
        sub = abl[abl.model == mid]
        means = []
        for c in cond_order:
            v = sub[sub.condition == c]["target_rank"].dropna().values
            v = v[v > 0]
            means.append(float(np.mean(v)) if len(v) else float("nan"))
        offs = (i - len(models) / 2 + 0.5) * width
        ax.bar(x + offs, means, width=width, color=color)
    ax.set_xticks(x); ax.set_xticklabels(cond_labels, rotation=22, ha="right")
    ax.set_yscale("log")
    ax.set_ylabel("mean target rank (log)")
    ax.set_title("(c) Target rank (lower = better)")
    ax.grid(True, alpha=0.3, axis="y", which="both")
    ax.set_xlim(-0.5, len(cond_order) - 0.5)

    legend_handles = [plt.Rectangle((0, 0), 1, 1, color=c) for (_, _, _, c) in models]
    legend_labels = [s for (_, s, _, _) in models]
    fig.legend(legend_handles, legend_labels, loc="lower center",
               ncol=len(models), fontsize=10, frameon=True, framealpha=0.92,
               bbox_to_anchor=(0.5, -0.04))
    fig.tight_layout(rect=[0, 0.04, 1, 1])
    fig.savefig(FIGS / "fig4_ablation.png", dpi=160, bbox_inches="tight")
    fig.savefig(FIGS / "fig4_ablation.pdf", bbox_inches="tight")
    plt.close(fig)
    print(f"  fig4 → {FIGS / 'fig4_ablation.png'}")

    # Export contrast table (truncate − full)
    rows = []
    for mid, short, fam, color in models:
        sub = abl[abl.model == mid]
        full = sub[sub.condition == "full_repeat_N30"].set_index("target_word")["target_prob"]
        trunc = sub[sub.condition == "truncate_to_N3"].set_index("target_word")["target_prob"]
        common = full.index.intersection(trunc.index)
        d = (trunc.loc[common] - full.loc[common]).dropna().values
        if len(d) == 0:
            continue
        rng2 = np.random.default_rng(42)
        boots = [d[rng2.integers(0, len(d), size=len(d))].mean() for _ in range(500)]
        lo, hi = float(np.percentile(boots, 2.5)), float(np.percentile(boots, 97.5))
        full_r = sub[sub.condition == "full_repeat_N30"].set_index("target_word")["target_rank"].mean()
        trunc_r = sub[sub.condition == "truncate_to_N3"].set_index("target_word")["target_rank"].mean()
        rows.append({"model": mid, "model_short": short, "n_words": int(len(d)),
                     "mean_diff": float(d.mean()), "ci_lo": lo, "ci_hi": hi,
                     "rank_full": float(full_r), "rank_trunc": float(trunc_r)})
    pd.DataFrame(rows).to_csv(SUMMARY / "ablation_contrasts.csv", index=False)


# ===========================================================================
# Figure 4 — mechanism probes
# ===========================================================================
def fig5_mechanism():
    fig, axes = plt.subplots(1, 3, figsize=(15.4, 5.0))
    ax_a, ax_b, ax_c = axes

    for mid, short, fam, color in MECH_MODELS:
        attn_path = DATA / f"mechanism/attention_last_layer__{_safe(mid)}.csv"
        slot_path = DATA / f"mechanism/slot_state__{_safe(mid)}.csv"

        if attn_path.exists():
            a = pd.read_csv(attn_path)
            agg = (a.groupby("N").agg(per_token=("attn_per_target_token", "mean"),
                                       total=("attn_total_to_target_block", "mean"))
                    .reset_index().sort_values("N"))
            agg = agg[agg["N"] > 0]
            if not agg.empty and not np.isnan(agg["per_token"]).all():
                n0 = agg["N"].iloc[0]; v0 = agg["per_token"].iloc[0]
                ax_a.plot(agg["N"], agg["per_token"], marker="o", color=color,
                          linewidth=2.2, label=short)
                ref = v0 * (n0 / agg["N"].astype(float))
                ax_a.plot(agg["N"], ref, linestyle="--", color=color,
                          linewidth=1.5, alpha=0.95, dashes=(4, 3))
                ax_b.plot(agg["N"], agg["total"], marker="s", color=color,
                          linewidth=2.2, label=short)

        if slot_path.exists():
            s = pd.read_csv(slot_path)
            tp = s.groupby("N")["target_prob"].mean().sort_index()
            tp = tp[tp.index > 0]
            ax_c.plot(tp.index, tp.values, marker="o", color=color,
                      linewidth=2.2, label=short)

    ax_a.set_xlabel("repetitions in prefix $N$")
    ax_a.set_ylabel("per-target-token attention (log)")
    ax_a.set_title(r"(a) Per-token attention vs $1/N$ reference (dashed)")
    ax_a.set_yscale("log")
    ax_a.grid(True, alpha=0.3, which="both")

    ax_b.set_xlabel("repetitions in prefix $N$")
    ax_b.set_ylabel("total attention to repetition block")
    ax_b.set_title("(b) Total block budget vs $N$")
    ax_b.grid(True, alpha=0.3)

    ax_c.set_xlabel("repetitions in prefix $N$")
    ax_c.set_ylabel("mean P(target) (mechanism subset)")
    ax_c.set_title("(c) Slot-state target probability")
    ax_c.grid(True, alpha=0.3)

    legend_handles = [Line2D([0], [0], color=c, marker="o", linewidth=2.2, label=s)
                      for (_, s, _, c) in MECH_MODELS]
    ref_handle = Line2D([0], [0], color="grey", linestyle="--", linewidth=1.5,
                        dashes=(4, 3),
                        label=r"$1/N$ reference (dashed, panel a only)")
    fig.legend(handles=legend_handles + [ref_handle], loc="lower center",
               ncol=len(MECH_MODELS) + 1, fontsize=10, frameon=True,
               framealpha=0.92, bbox_to_anchor=(0.5, -0.04))
    fig.tight_layout(rect=[0, 0.04, 1, 1])
    fig.savefig(FIGS / "fig5_mechanism.png", dpi=160, bbox_inches="tight")
    fig.savefig(FIGS / "fig5_mechanism.pdf", bbox_inches="tight")
    plt.close(fig)
    print(f"  fig5 → {FIGS / 'fig5_mechanism.png'}")


# ===========================================================================
# Figure (Appendix) layerwise — per-layer attention vs 1/N reference
# ===========================================================================
def _per_layer_attention_ratio(df_attn):
    """Return DataFrame indexed by (layer, N) with log2(per_token / 1/N reference)."""
    g = (df_attn.groupby(["layer", "N"])
         .agg(per_token=("attn_per_target_token", "mean"),
              total=("attn_total_to_target_block", "mean"))
         .reset_index())
    refs = g[g.N == g.N.min()].set_index("layer")["per_token"]
    g["ref"] = g.apply(lambda r: refs.get(r.layer, np.nan) * (g.N.min() / r.N), axis=1)
    g["log2_ratio"] = np.log2(g["per_token"].clip(lower=1e-9) / g["ref"].clip(lower=1e-9))
    return g


def fig6_layerwise():
    NS_LW = [1, 3, 5, 10, 20, 30]
    LW_PANEL = [(m, s, f) for (m, s, f, _) in MECH_MODELS]

    fig, axes = plt.subplots(1, 4, figsize=(15.4, 4.6),
                             gridspec_kw=dict(width_ratios=[1, 1, 1, 1.07]))
    # Diverging cmap with luminance-asymmetric endpoints so super-dilution
    # (dark purple) and sub-dilution (orange) remain distinguishable in
    # grayscale. Purple Y≈0.28 vs orange Y≈0.60.
    cmap = LinearSegmentedColormap.from_list(
        "po", [(0.34, 0.20, 0.54), (1.0, 1.0, 1.0), (1.0, 0.50, 0.07)])

    last_im = None
    for ax, (mid, short, fam) in zip(axes, LW_PANEL):
        f = DATA / "layerwise" / f"layerwise__{_safe(mid)}.parquet"
        if not f.exists():
            ax.set_title(f"{short}: missing"); continue
        df = pd.read_parquet(f)
        df = df[df.metric == "attention"]
        df = df[(df.N > 0) & (df.n_target_positions > 0)]
        df = df.dropna(subset=["attn_per_target_token", "layer"])
        df["layer"] = df["layer"].astype(int)
        if df.empty:
            ax.set_title(f"{short}: no attn data"); continue

        g = _per_layer_attention_ratio(df)
        H = g.pivot_table(index="layer", columns="N", values="log2_ratio", aggfunc="mean")
        cols = [n for n in NS_LW if n in H.columns]
        # Drop the anchor column: by construction log2_ratio at N=min is
        # identically 0 (per-token attn equals its own reference), so the
        # leftmost column is structurally white and carries no information.
        if cols:
            cols = cols[1:]
        if not cols or H.empty:
            ax.set_title(f"{short}: empty"); continue
        H = H[cols].sort_index()
        Hv = np.clip(np.nan_to_num(H.values, nan=0.0), -3, 3)
        n_layers = int(H.index.max())
        im = ax.imshow(Hv, aspect="auto", cmap=cmap, vmin=-3, vmax=3,
                       extent=[-0.5, len(cols) - 0.5,
                               n_layers + 0.5, int(H.index.min()) - 0.5])
        ax.set_xticks(range(len(cols)))
        ax.set_xticklabels([str(n) for n in cols])
        ax.set_xlabel("$N$")
        ax.set_title(f"{short}\n({fam}, {n_layers} layers)")
        if ax is axes[0]:
            ax.set_ylabel("layer")
        last_im = im

    if last_im is not None:
        cbar = fig.colorbar(last_im, ax=axes[-1], fraction=0.04, pad=0.04)
        cbar.set_label(r"$\log_{2}$(per-token attn / $1/N$ ref.)", fontsize=9)
        cbar.ax.tick_params(labelsize=8)

    fig.tight_layout()
    fig.savefig(FIGS / "fig6_layerwise.png", dpi=160, bbox_inches="tight")
    fig.savefig(FIGS / "fig6_layerwise.pdf", bbox_inches="tight")
    plt.close(fig)
    print(f"  fig6 → {FIGS / 'fig6_layerwise.png'}")


def fig7_framepragm():
    fp_files = sorted((DATA / "frame_pragmatics").glob("frame_pragmatics__*.parquet"))
    if not fp_files:
        print("  no frame_pragmatics files; skipping fig7"); return
    fp = pd.concat([pd.read_parquet(f) for f in fp_files], ignore_index=True)
    classes = ["ORIG", "NEUTRAL", "ANAPHORIC", "NOVELTY"]
    labels = {"ORIG": "Topic-introducer (F0,F2)", "NEUTRAL": "Neutral / existential",
              "ANAPHORIC": "Anaphoric (demands repeat)", "NOVELTY": "Novelty (demands new word)"}
    colors = {"ORIG": "#1f77b4", "NEUTRAL": "#ff7f0e", "ANAPHORIC": "#2ca02c", "NOVELTY": "#d62728"}
    models = [(m, s) for (m, s, fam, c) in MECH_MODELS if m in fp["model"].unique()]
    fig, axes = plt.subplots(1, len(models), figsize=(15.4, 4.0), sharey=True, squeeze=False)
    for ax, (mid, short) in zip(axes[0], models):
        sub_m = fp[fp.model == mid]
        for cls in classes:
            sub = sub_m[sub_m.frame_class == cls]
            if sub.empty:
                continue
            mc = sub.groupby("N")["target_prob"].mean().reindex(NS)
            denom = mc.reindex(NS_NONZERO).max()
            ax.plot(NS, (mc / denom).values, marker="o", ms=4.5, lw=1.8,
                    color=colors[cls], label=labels[cls], zorder=3)
            pk = int(mc.reindex(NS_NONZERO).idxmax())
            ax.plot([pk], [mc[pk] / denom], marker="o", ms=7, mfc="white",
                    mec=colors[cls], mew=1.6, zorder=4)
        ax.axhline(1.0, ls=":", c="0.6", lw=0.8)
        ax.set_title(short)
        ax.set_xlabel("N (target repetitions)")
        ax.set_xticks([0, 5, 10, 15, 20, 25, 30])
        ax.grid(True, alpha=0.3)
        ax.set_ylim(-0.05, 1.08)
    axes[0][0].set_ylabel("peak-normalised mean $P$(target)")
    h, l = axes[0][0].get_legend_handles_labels()
    fig.legend(h, l, loc="lower center", ncol=4, frameon=True, framealpha=0.92,
               bbox_to_anchor=(0.5, -0.02), fontsize=9.5)
    fig.tight_layout(rect=[0, 0.07, 1, 1])
    fig.savefig(FIGS / "fig7_framepragm.png", dpi=160, bbox_inches="tight")
    fig.savefig(FIGS / "fig7_framepragm.pdf", bbox_inches="tight")
    plt.close(fig)
    print(f"  fig7 -> {FIGS / 'fig7_framepragm.png'}")


# ===========================================================================
# CLI
# ===========================================================================
FIGURES = {
    "fig2":  fig2_main_curves,
    "fig3":  fig3_crosslingual,
    "fig4":  fig4_ablation,
    "fig5":  fig5_mechanism,
    "fig6":  fig6_layerwise,
    "fig7":  fig7_framepragm,
}


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("figures", nargs="*",
                   help=f"subset to regenerate (default: all). "
                        f"Choices: {', '.join(FIGURES.keys())}")
    args = p.parse_args(argv)
    targets = args.figures or list(FIGURES)
    bad = [t for t in targets if t not in FIGURES]
    if bad:
        sys.exit(f"unknown figure(s): {bad}; choose from {list(FIGURES)}")
    for t in targets:
        FIGURES[t]()
    print("done")


if __name__ == "__main__":
    main()
